version: '3.4'

services:
  colegioelasticsearch:
    image: registry.gitlab.com/danytorres/colegio-elastic:latest
    # build: .
    # command: ["bash","migrate.sh"]
    # entrypoint: ["bash","migrate.sh"]
    volumes:
      - ./elastic/server:/app/server
    depends_on:
      - db
      - es01
    networks:
      - elastic
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=elasticSearch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - data02:/var/lib/postgresql/data
    networks:
      - elastic
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./elastic/server/static:/home/app/microservice/static
      - ./elastic/server/uploads:/home/app/microservice/uploads
    depends_on:
      - colegioelasticsearch
    restart: "on-failure"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  data01:
    driver: local
  data02:
    driver: local